client_config_backend: 'file'
client_config:
  client_id: "155971301371-lcra6sehufnkbfn9mdiuu5mfahrdbcm7.apps.googleusercontent.com"
  client_secret: "6fxEFM4gPuMIDSsYu-DwOirC"

save_credentials: True
save_credentials_backend: 'file'
save_credentials_file: 'credentials.json'

oauth_scope:
  - "https://www.googleapis.com/auth/drive"
